// ============================================================
// DOCTOR SUMMARY (Weekly report — PDF + WhatsApp shareable)
// ============================================================
const DoctorSummary = ({ state, onAddNote, onAddContextNote }) => {
  const { baby, events, weightLog, milestones, appointments, healthLog, contextNotes } = state;
  const ageWeeks = baby?.birthDate ? getBabyAgeWeeks(baby.birthDate) : 0;
  const [period, setPeriod] = useState("7d");
  const [copied, setCopied] = useState(false);
  const [showAddNote, setShowAddNote] = useState(false);
  const [noteText, setNoteText] = useState("");
  const [showAddAppt, setShowAddAppt] = useState(false);
  const [apptTitle, setApptTitle] = useState("");
  const [apptDate, setApptDate] = useState("");
  const [apptTime, setApptTime] = useState("");
  const [apptNotes, setApptNotes] = useState("");
  const givenVaccines = (() => { try { return JSON.parse(localStorage.getItem("given_vaccines") || "[]"); } catch(e) { return []; } })();

  const periodDays = period === "7d" ? 7 : period === "14d" ? 14 : 30;
  const now = new Date();
  const start = new Date(now); start.setDate(start.getDate() - periodDays);

  const periodEvents = events.filter((e) => new Date(e.timestamp) >= start);
  const feeds = periodEvents.filter((e) => e.type === "feed");
  const sleeps = periodEvents.filter((e) => e.type === "sleep");
  const diapers = periodEvents.filter((e) => e.type === "diaper");
  const totalSleepH = (sleeps.reduce((s, e) => s + (e.duration || 0), 0) / 3600000 / periodDays).toFixed(1);
  const avgFeeds = (feeds.length / periodDays).toFixed(1);
  const avgDiapers = (diapers.length / periodDays).toFixed(1);
  const stools = diapers.filter((d) => d.content === "stool" || d.content === "both");
  const stoolColors = [...new Set(stools.map((d) => d.stoolColor).filter(Boolean))];
  const latestWeight = weightLog.length > 0 ? weightLog[weightLog.length - 1] : null;
  const achievedMilestones = (milestones || []).filter((m) => m.achievedDate);
  const recentHealth = (healthLog || []).filter((h) => new Date(h.timestamp) >= start);
  const activeNotes = (contextNotes || []).filter((n) => n.active);

  const summaryText = () => {
    let t = `BABY HEALTH SUMMARY\n`;
    t += `${"=".repeat(30)}\n`;
    t += `Baby: ${baby?.name || "Baby"}\n`;
    t += `Age: ${ageWeeks} weeks (${formatAge(baby?.birthDate)})\n`;
    t += `Period: Last ${periodDays} days (${formatDate(start)} - ${formatDate(now)})\n\n`;
    t += `FEEDING\n`;
    t += `• Average: ${avgFeeds} feeds/day\n`;
    t += `• Total sessions: ${feeds.length}\n`;
    const breastFeeds = feeds.filter((f) => f.feedType === "breast");
    const exprFeeds = feeds.filter((f) => f.feedType === "expression");
    const formulaFeeds = feeds.filter((f) => f.feedType === "formula");
    if (breastFeeds.length) t += `• Breast: ${breastFeeds.length} (${Math.round(breastFeeds.length/feeds.length*100)}%)\n`;
    if (exprFeeds.length) t += `• Expression: ${exprFeeds.length} (${Math.round(exprFeeds.length/feeds.length*100)}%)\n`;
    if (formulaFeeds.length) t += `• Formula: ${formulaFeeds.length} (${Math.round(formulaFeeds.length/feeds.length*100)}%)\n`;
    t += `\nSLEEP\n`;
    t += `• Average: ${totalSleepH}h/day\n`;
    t += `• Total sessions: ${sleeps.length}\n`;
    t += `\nDIAPERS\n`;
    t += `• Average: ${avgDiapers}/day\n`;
    t += `• Stools: ${stools.length} total\n`;
    if (stoolColors.length) t += `• Stool colors: ${stoolColors.join(", ")}\n`;
    if (latestWeight) { t += `\nWEIGHT\n`; t += `• Latest: ${latestWeight.weight} ${latestWeight.unit} (${formatDate(latestWeight.date)})\n`; }
    if (recentHealth.length) { t += `\nHEALTH NOTES\n`; recentHealth.forEach((h) => { t += `• ${h.emoji} ${h.label} (${formatDate(h.timestamp)})\n`; }); }
    if (activeNotes.length) { t += `\nACTIVE CONCERNS\n`; activeNotes.forEach((n) => { t += `• ${n.text}${n.explanation ? " — " + n.explanation : ""} (since ${formatDate(n.createdAt)})\n`; }); }
    if (achievedMilestones.length) { t += `\nMILESTONES ACHIEVED\n`; achievedMilestones.slice(-5).forEach((m) => { const def = WHO_MILESTONES.find((w) => w.id === m.milestoneId); if (def) t += `• ${def.title} (${formatDate(m.achievedDate)})\n`; }); }
    const givenVax = VACCINATION_SCHEDULE_BASE.filter((v) => givenVaccines.includes(v.name));
    const pendingVax = VACCINATION_SCHEDULE_BASE.filter((v) => !givenVaccines.includes(v.name) && v.weekDue <= ageWeeks + 4);
    if (givenVax.length) { t += `\nVACCINATIONS GIVEN (${givenVax.length})\n`; givenVax.forEach((v) => { t += `• ${v.name} (Week ${v.weekDue})\n`; }); }
    if (pendingVax.length) { t += `\nVACCINATIONS PENDING\n`; pendingVax.forEach((v) => { t += `• ${v.name} (Week ${v.weekDue})\n`; }); }
    t += `\n---\nGenerated by Tiny Steps on ${new Date().toLocaleDateString()}`;
    return t;
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(summaryText()).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
  };

  const shareWhatsApp = () => {
    window.open(`https://wa.me/?text=${encodeURIComponent(summaryText())}`, "_blank");
  };

  const downloadPDF = () => {
    const text = summaryText();
    const lines = text.split("\n");
    let html = "<html><head><style>body{font-family:Arial,sans-serif;padding:40px;max-width:600px;margin:0 auto;color:#1a1a2e}h1{color:#5B7FFF;font-size:20px}h2{color:#6B7280;font-size:14px;text-transform:uppercase;margin-top:20px;border-bottom:1px solid #eee;padding-bottom:4px}p{margin:4px 0;font-size:13px}hr{border:none;border-top:1px solid #eee;margin:16px 0}.footer{color:#9CA3AF;font-size:11px;margin-top:24px}</style></head><body>";
    lines.forEach((line) => {
      if (line.startsWith("BABY HEALTH")) html += `<h1>👶 ${line}</h1>`;
      else if (line.startsWith("===")) return;
      else if (line === "FEEDING" || line === "SLEEP" || line === "DIAPERS" || line === "WEIGHT" || line === "HEALTH NOTES" || line === "ACTIVE CONCERNS" || line === "MILESTONES ACHIEVED") html += `<h2>${line}</h2>`;
      else if (line.startsWith("•")) html += `<p>${line}</p>`;
      else if (line.startsWith("---")) html += "<hr>";
      else if (line.startsWith("Generated")) html += `<p class=\"footer\">${line}</p>`;
      else if (line.trim()) html += `<p><strong>${line}</strong></p>`;
    });
    html += "</body></html>";
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${baby?.name || "baby"}-summary-${toDateKey(new Date())}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={S.page}>
      <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Doctor Summary</h2>
      <p style={{ fontSize: 13, color: C.t2, marginBottom: 16 }}>Share with your pediatrician</p>

      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        {[["7d", "7 Days"], ["14d", "2 Weeks"], ["30d", "30 Days"]].map(([id, label]) => (
          <button key={id} style={S.chip(period === id, C.pri)} onClick={() => setPeriod(id)}>{label}</button>
        ))}
      </div>

      {/* Preview */}
      <div style={{ ...S.card, background: C.bg }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
          <span style={{ fontSize: 20 }}>👶</span>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700 }}>{baby?.name || "Baby"}</div>
            <div style={{ fontSize: 12, color: C.t3 }}>{ageWeeks} weeks · Last {periodDays} days</div>
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>
          <div style={S.stat(C.feed)}><div style={{ fontSize: 10, color: C.t2, fontWeight: 600 }}>FEEDS/DAY</div><div style={{ fontSize: 20, fontWeight: 700, color: C.feed }}>{avgFeeds}</div></div>
          <div style={S.stat(C.sleep)}><div style={{ fontSize: 10, color: C.t2, fontWeight: 600 }}>SLEEP/DAY</div><div style={{ fontSize: 20, fontWeight: 700, color: C.sleep }}>{totalSleepH}h</div></div>
          <div style={S.stat(C.diaper)}><div style={{ fontSize: 10, color: C.t2, fontWeight: 600 }}>DIAPERS/DAY</div><div style={{ fontSize: 20, fontWeight: 700, color: C.diaper }}>{avgDiapers}</div></div>
          <div style={S.stat(C.weight)}><div style={{ fontSize: 10, color: C.t2, fontWeight: 600 }}>WEIGHT</div><div style={{ fontSize: 20, fontWeight: 700, color: C.weight }}>{latestWeight ? `${latestWeight.weight}${latestWeight.unit}` : "—"}</div></div>
        </div>

        {recentHealth.length > 0 && (
          <div style={{ marginBottom: 12 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: C.danger, marginBottom: 4 }}>Health Notes</div>
            {recentHealth.map((h, i) => (<div key={i} style={{ fontSize: 12, color: C.t2, padding: "2px 0" }}>{h.emoji} {h.label} — {formatDate(h.timestamp)}</div>))}
          </div>
        )}

        {activeNotes.length > 0 && (
          <div style={{ marginBottom: 12 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: C.warning, marginBottom: 4 }}>Active Concerns</div>
            {activeNotes.map((n, i) => (<div key={i} style={{ fontSize: 12, color: C.t2, padding: "2px 0" }}>📌 {n.text}</div>))}
          </div>
        )}

        {stoolColors.length > 0 && (
          <div style={{ fontSize: 12, color: C.t2, marginBottom: 8 }}>Stool colors observed: {stoolColors.join(", ")}</div>
        )}
      </div>

      {/* Vaccinations Given */}
      <div style={S.card}>
        <h3 style={{ fontSize: 14, fontWeight: 700, color: C.vaccine, marginBottom: 8 }}>💉 Vaccinations</h3>
        <div style={{ fontSize: 12, color: C.success, marginBottom: 8 }}>{givenVaccines.length} given</div>
        {VACCINATION_SCHEDULE_BASE.filter((v) => givenVaccines.includes(v.name)).map((v, i) => (
          <div key={i} style={{ fontSize: 12, color: C.t2, padding: "3px 0" }}>✅ {v.name} · {v.description}</div>
        ))}
        {VACCINATION_SCHEDULE_BASE.filter((v) => !givenVaccines.includes(v.name) && v.weekDue <= ageWeeks + 4).length > 0 && (
          <>
            <div style={{ fontSize: 12, fontWeight: 600, color: C.warning, marginTop: 8, marginBottom: 4 }}>Upcoming / Pending</div>
            {VACCINATION_SCHEDULE_BASE.filter((v) => !givenVaccines.includes(v.name) && v.weekDue <= ageWeeks + 4).map((v, i) => (
              <div key={i} style={{ fontSize: 12, color: C.t3, padding: "3px 0" }}>⏳ {v.name} · Week {v.weekDue}</div>
            ))}
          </>
        )}
      </div>

      {/* Add Notes */}
      <div style={S.card}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: C.t2 }}>📝 Notes for Doctor</h3>
          <button style={{ ...S.btn("secondary"), padding: "6px 12px", fontSize: 12 }} onClick={() => setShowAddNote(!showAddNote)}>+ Add Note</button>
        </div>
        {showAddNote && (
          <div style={{ marginBottom: 12 }}>
            <input style={{ ...S.input, marginBottom: 8 }} value={noteText} onChange={(e) => setNoteText(e.target.value)} placeholder="e.g. Baby had mild rash on left cheek..." />
            <button style={{ ...S.btn("primary"), width: "100%", opacity: noteText ? 1 : 0.5 }} onClick={() => { if (noteText && onAddNote) { onAddNote({ id: generateId(), text: noteText, timestamp: new Date().toISOString() }); setNoteText(""); setShowAddNote(false); } }}>Save Note</button>
          </div>
        )}
        {(healthLog || []).slice(0, 10).map((h, i) => (
          <div key={i} style={{ fontSize: 12, color: C.t2, padding: "4px 0", borderBottom: `1px solid ${C.borderL}` }}>{h.emoji || "📌"} {h.label || h.text} · {formatDate(h.timestamp)}</div>
        ))}
        {(!healthLog || healthLog.length === 0) && <p style={{ fontSize: 12, color: C.t3 }}>No notes yet. Add observations for your next doctor visit.</p>}
      </div>

      {/* Add Google Calendar Appointment */}
      <div style={S.card}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
          <h3 style={{ fontSize: 14, fontWeight: 700, color: C.doctor }}>📅 Doctor Appointment</h3>
          <button style={{ ...S.btn("secondary"), padding: "6px 12px", fontSize: 12 }} onClick={() => setShowAddAppt(!showAddAppt)}>+ Schedule</button>
        </div>
        {showAddAppt && (
          <div style={{ marginBottom: 12 }}>
            <label style={S.label}>Title</label>
            <input style={{ ...S.input, marginBottom: 8 }} value={apptTitle} onChange={(e) => setApptTitle(e.target.value)} placeholder="e.g. 2-month checkup" />
            <label style={S.label}>Date</label>
            <input style={{ ...S.input, marginBottom: 8 }} type="date" value={apptDate} onChange={(e) => setApptDate(e.target.value)} />
            <label style={S.label}>Time</label>
            <input style={{ ...S.input, marginBottom: 8 }} type="time" value={apptTime} onChange={(e) => setApptTime(e.target.value)} />
            <label style={S.label}>Notes for Doctor</label>
            <input style={{ ...S.input, marginBottom: 8 }} value={apptNotes} onChange={(e) => setApptNotes(e.target.value)} placeholder="Include any concerns..." />
              <button onClick={() => { const d = (apptDate||"20260101").replace(/-/g,""); const t = (apptTime||"09:00").replace(/:/g,""); const t2 = String(Math.min(23,parseInt((apptTime||"09:00").split(":")[0])+1)).padStart(2,"0") + (apptTime||"09:00").split(":")[1]; const url = "https://www.google.com/calendar/render?action=TEMPLATE&text=" + encodeURIComponent((apptTitle || "Doctor Visit") + " - " + (baby?.name || "Baby")) + "&dates=" + d + "T" + t + "00/" + d + "T" + t2 + "00&details=" + encodeURIComponent((apptNotes || "") + "\n\n" + summaryText()); window.open(url, "_blank"); }} style={{ ...S.btn("primary"), width: "100%", opacity: apptDate ? 1 : 0.5 }}>
              📅 Add to Google Calendar
            </button>
            <p style={{ fontSize: 10, color: C.t3, marginTop: 6, textAlign: "center" }}>Opens Google Calendar with the summary auto-filled in the description</p>
          </div>
        )}
        {appointments.filter((a) => !a.completed && new Date(a.date) >= new Date()).slice(0, 3).map((a, i) => (
          <div key={i} style={{ fontSize: 12, color: C.t2, padding: "4px 0" }}>{a.type === "vaccination" ? "💉" : "🩺"} {a.title} · {formatDate(a.date)}</div>
        ))}
      </div>

      {/* Share Actions */}
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        <button style={{ ...S.btn("primary"), width: "100%" }} onClick={shareWhatsApp}>
          📱 Share via WhatsApp
        </button>
        <button style={{ ...S.btn("secondary"), width: "100%" }} onClick={copyToClipboard}>
          {copied ? "✓ Copied!" : "📋 Copy Summary Text"}
        </button>
        <button style={{ ...S.btn("secondary"), width: "100%" }} onClick={downloadPDF}>
          📄 Download Report (HTML)
        </button>
      </div>
    </div>
  );
};

